function workingSite() {
var band = [
"https://open.spotify.com/album/7AzLY3OCx0xrzCYMlIopRh",
"https://open.spotify.com/album/1Fhuozeg9xpG61Oa6LMFxL",
"https://open.spotify.com/album/1gb8ZDw01lAHZRQVFuHwcM",
"https://open.spotify.com/album/0jS2XwnBHNNbhekip9kfSM",
"https://open.spotify.com/album/7behJdMRaGWSyXdzkg1hyi",
"https://open.spotify.com/album/6N3hrl7KzFVe4lTMohpO03",
"https://open.spotify.com/album/7xmptzhNwe5qzogmMGosKO",
"https://open.spotify.com/album/1a1K5r92gK3xGpM7K7xVzk",
"https://open.spotify.com/album/5ZGHnnXzO1REd4PiN2s2fB",
"https://open.spotify.com/album/2afxPgGqLlFrolXijoKb4L",
"https://open.spotify.com/album/01cJcrn4l6n9ScZnqn35ir",
"https://open.spotify.com/album/3cvqgz09TZKq9KHPCfTVdU",
"https://open.spotify.com/album/2usDuczD98n3Eqg79QAR4Y",
"https://open.spotify.com/album/5yXAHOZ96y7fj5j1XiX3K8",
"https://open.spotify.com/album/7imORAK8Qa40pbKJILg8BT",
"https://open.spotify.com/album/41PfMaFddHOcxxkvbycHga",
"https://open.spotify.com/album/7AiWJCZ2HArLkWG8HdPgIQ",
"https://open.spotify.com/album/2L1b9sSISE7oE3Y2B1UlBx",
"https://open.spotify.com/album/13aBC6LtPybtYKtMMDdE4W",
"https://open.spotify.com/album/325N6QCurdWQX8uCDK7EkJ",
"https://open.spotify.com/album/5YIy67yOuivSYObR3sbj6W",
"https://open.spotify.com/album/0aBiILh0LZalPkT0ve0RBs",
"https://open.spotify.com/album/2gWGiNp10JRlsP0wnkJqJf",
"https://open.spotify.com/album/4Mw4KC7LipiviZTWhXrAhs",
"https://open.spotify.com/album/6oInPicMsvi5ufwK34YCLE",
"https://open.spotify.com/album/7brzNHopjosNw2ddDMjtwg",
"https://open.spotify.com/album/7BSe2EAPUNskkzwCrVfVTp",
"https://open.spotify.com/album/2BD06kPNevR4EL4yqaUqOP",
"https://open.spotify.com/album/7LYUo2bfaJ3T5HvOQVaADr",
"https://open.spotify.com/album/6ZWeoJI6945xP5KLEgsIl5",
"https://open.spotify.com/album/2u3CQWMZNFURXVVYSMxWbM",
"https://open.spotify.com/album/5ZLtFPkZbnAPKeGqRrpQYd",
"https://open.spotify.com/album/14H2rmBLU6VxXpNfdpRh1z",
"https://open.spotify.com/album/5SAzfGrSwd1QaDGMirBU5e",
"https://open.spotify.com/album/7oHAH6BfMwDcSLI1YyxU81",
"https://open.spotify.com/album/3ioBNl4CKZfJVbyA2ZHHpU",
"https://open.spotify.com/album/2i3825q36PqJHlqHdZFZBE",
"https://open.spotify.com/album/1BLsgB0FPErCgus7t3nTi3",
"https://open.spotify.com/album/7INulFwDmgAPwExbaeAWoH",
"https://open.spotify.com/album/7eVY0677xRMK8I4syfRA6M",
"https://open.spotify.com/album/3cSB5MsWScPMNvKPoDeaL0",
"https://open.spotify.com/album/5883TvzGSwcBuhAafpDVr0",
"https://open.spotify.com/album/56lgaaW0izVKXThsk9cqLE",
"https://open.spotify.com/album/2QdexRzNUXkbHyHoVfrtaj",
"https://open.spotify.com/album/3LuBwIxzgfo9579smrH6Uf",
"https://open.spotify.com/album/2QKwnysUYSxmob2CLQTMMh",
"https://open.spotify.com/album/0VM6c3NXOlaa9LKl4dOnFV",
"https://open.spotify.com/album/76ocBsKdXaFbL1edOyA6aC",
"https://open.spotify.com/album/51Feoswkepa9SEg307gah5",
"https://open.spotify.com/album/3qMeTFrogtWfk4gGOfVNX7",
"https://open.spotify.com/album/0Uh7J2iz5f2zRwAo2MaNhJ",
"https://open.spotify.com/album/6WDdeivbRK1JTsVKaY5mD4",
"https://open.spotify.com/album/5TNwDJK182ibDNObp5DclP",
"https://open.spotify.com/album/102yfMNPzomYhs88RBvPGu",
"https://open.spotify.com/album/5121LhU4bcS1DsL7Y33Iqf",
"https://open.spotify.com/album/3awjfAkmTKgNcFdGk8So8M",
"https://open.spotify.com/album/6hGIYmbgyD2Hd0K9wMbV82",
"https://open.spotify.com/album/2MCKoonObhYFkWb5azuVNM",
"https://open.spotify.com/album/3yYGTngHasHWWeyZ4SFQzx",
"https://open.spotify.com/album/5dcLbUaWSJPcYykHbhEIBs",
"https://open.spotify.com/album/4typKG5HG3aKrZTcTUs5gR",
"https://open.spotify.com/album/5jY6HJRJZeVvziOcG3QGZB",
"https://open.spotify.com/album/1tQu54ijI8xXIQxOLYPQzL",
"https://open.spotify.com/album/4q9E5jAAcVTutsH2Ctpwhb",
"https://open.spotify.com/album/3tTqblrxKo5ZvuhWSg8zRy",
"https://open.spotify.com/album/7wEBUUbQvLH2zkT23SE06V",
"https://open.spotify.com/album/7hzNKDHipGQFPBHVboIFb6",
"https://open.spotify.com/album/2TxnZ116PhDVXyGnW3OwxB",
"https://open.spotify.com/album/3lXeEthVaUmwtyKj0myPnZ",
"https://open.spotify.com/album/3vz1t2QAMI7HO3l049XyMt",
"https://open.spotify.com/album/7o6ODFrS8G6YgwY7bsAR1W",
"https://open.spotify.com/album/3fcDrMOfECm2nZwwp9Nbge",
"https://open.spotify.com/album/3kdaoYi2SztpyarxBZ3py6",
"https://open.spotify.com/album/1p2J99ueyaBixV8hp266uz",
"https://open.spotify.com/album/3uF0eDO6FcdBSJcR4wdwms",
"https://open.spotify.com/album/2uSeSoosBWMI0bYbvBwJAm",
"https://open.spotify.com/album/6Ueh56mt7zYq80ryGgWNJR",
"https://open.spotify.com/album/5CNcTVrgGUXPTewHvOFzlv",
"https://open.spotify.com/album/1xZmDyFDswCegCLRZYvqRf",
"https://open.spotify.com/album/4FE3aH9bVAAFMBVSNPxKIT",
"https://open.spotify.com/album/5sawDVKUv5o4j1KU8JUyEP",
"https://open.spotify.com/album/5kCJfEVm8sBIcokWRAEQ3F",
"https://open.spotify.com/album/4lOnrRZSE2reAglgOmzLel",
"https://open.spotify.com/album/0OXi26j1IAohfBcODo60dN",
"https://open.spotify.com/album/0i1XEyBtfS6LdSW572R8H8",
"https://open.spotify.com/album/5JtW9TU74xyVtRQXjjLpL1",
"https://open.spotify.com/album/0h7WAAvFPveqgL5Ftjfqig",
"https://open.spotify.com/album/2dKZvc9JhER975n3kxPYZu",
"https://open.spotify.com/album/1KMVxVoX3inBf9aCVcFS1P",
"https://open.spotify.com/album/3LMsFkOLJImsFFUddEjLDy",
"https://open.spotify.com/album/2UaTxbzX0NWE81YpK7Xgeb",
"https://open.spotify.com/album/5wqBi2juBdWCijxa1a5QFk",
"https://open.spotify.com/album/60v8QWUtub3PvY9G44swIy",
"https://open.spotify.com/album/3nJeN4aNv9MBY5XTzK64Qi",
"https://open.spotify.com/album/2aZvcRVFrg5J55lU7lvhs3",
"https://open.spotify.com/album/3DlS3knemmDez2gMIQ8ZqQ",
"https://open.spotify.com/album/4S5MLu2PKU7uElm2V3JphK",
"https://open.spotify.com/album/41aGoncUw8CbPqUTIJOVeM"
];



var generateBand = band[Math.floor(Math.random()*band.length)];
window.open(generateBand);

};







